### ISSUE TITLE
Exception when updating media added with v12

### ISSUE THREAD

**Issue by Insprill** [jellyfin/jellyfin-plugin-kodisyncqueue#104]
While debugging an issue with transcode failures, I noticed that whenever it fails, the Kodi Sync Queue always throws the following exception immediately after:
```
jellyfin-1  | 2024-11-27T06:25:46.818594055Z MediaBrowser.Common.FfmpegException: FFmpeg exited with code 183
...
jellyfin-1  | 2024-11-27T06:25:46.888633176Z [06:25:46] [INF] [14] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: Deleting partial stream file(s) /config/transcodes/39c3bc36b1cfe494e586f40ea0e8c2f3.m3u8
jellyfin-1  | 2024-11-27T06:25:48.392509416Z [06:25:48] [INF] [34] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app Jellyfin Web 10.10.3 playing [redacted]. Stopped at 0 ms
jellyfin-1  | 2024-11-27T06:25:48.893678277Z [06:25:48] [INF] [31] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification: Started user data sync
jellyfin-1  | 2024-11-27T06:25:48.935334956Z [06:25:48] [ERR] [31] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification: An error has occurred in UserUpdateTimerCallback
jellyfin-1  | 2024-11-27T06:25:48.935374802Z System.InvalidCastException: Unable to cast object of type 'System.Guid' to type 'System.String'.
jellyfin-1  | 2024-11-27T06:25:48.935380183Z    at lambda_method1255(Closure, Object, Object)
jellyfin-1  | 2024-11-27T06:25:48.935384764Z    at LiteDB.BsonMapper.DeserializeObject(EntityMapper entity, Object obj, BsonDocument value)
jellyfin-1  | 2024-11-27T06:25:48.935389208Z    at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
jellyfin-1  | 2024-11-27T06:25:48.935393432Z    at LiteDB.LiteQueryable`1.<ToEnumerable>b__27_2(BsonDocument x)
jellyfin-1  | 2024-11-27T06:25:48.935398232Z    at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
jellyfin-1  | 2024-11-27T06:25:48.935402456Z    at Jellyfin.Plugin.KodiSyncQueue.Data.DbRepo.SetUserInfoSync(List`1 dtos, List`1 itemRefs, String userId)
jellyfin-1  | 2024-11-27T06:25:48.935406832Z    at Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification.SaveUserChanges(List`1 dtos, List`1 itemRefs, String userName, String userId)
jellyfin-1  | 2024-11-27T06:25:48.935434379Z    at Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification.SendNotifications(IEnumerable`1 changes, List`1 itemRefs, CancellationToken cancellationToken)
jellyfin-1  | 2024-11-27T06:25:48.935438734Z    at Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification.UpdateTimerCallback(Object state)
```
**Jellyfin:** v10.10.3
**Kodi Sync Queue:** v13.0.0.0

**Comment by Ulrar** [comment]
Same here. Playback stops every few minutes for one user, not sure if it's related to this error but it's logging it, often

**Comment by Insprill** [comment]
Looking at #97 and #100, I'd assume this happens for any media added to the database with v12 installed. Is there a way to fix those database entries, or how should those affected proceed?

**Comment by Ulrar** [comment]
Can the db be cleared ?
I don't love the idea of talking everyone through a manual resync, but as long as the option doesn't turn itself off in people's Kodi it's do-able

**Comment by Insprill** [comment]
Why was this marked as a duplicate of #105? This issue is older and has more info about the actual cause.

**Comment by crobibero** [comment]
Because I had responded in that one. Typically the first issue would be the winner but I am the primary maintainer of plugins and I missed this issue.
