### ISSUE TITLE
UserUpdateTimerCallback System.InvalidCastException: Unable to cast object of type 'System.Guid' to type 'System.String'.

### ISSUE THREAD

**Issue by pimw1** [jellyfin/jellyfin-plugin-kodisyncqueue#105]
Hi,

The following error appears during playback of movies in Kodi, using CoreElec and the Jellyfin Kodi plugin. The initial sync during the boot of my client device (Ugoos AM6B+) is fine.

```
2024-12-07 13:58:05.962 +01:00] [INF] [8] Jellyfin.Plugin.KodiSyncQueue.API.KodiSyncQueueController: Plugin Settings Requested...
[2024-12-07 13:58:06.024 +01:00] [INF] [8] Jellyfin.Plugin.KodiSyncQueue.API.KodiSyncQueueController: Sync Requested for UserID: '"74404612e1a14b87b601d9b75d6d44cc"' with LastUpdateDT: '"2024-12-07T12:41:22z"'
[2024-12-07 13:58:06.203 +01:00] [INF] [8] Jellyfin.Plugin.KodiSyncQueue.API.KodiSyncQueueController: Added: 0, Removed: 0, Updated: 0, Changed User Data: 0
[2024-12-07 13:58:06.203 +01:00] [INF] [8] Jellyfin.Plugin.KodiSyncQueue.API.KodiSyncQueueController: Request Finished Taking "00:00:00.1739778"
[2024-12-07 13:58:38.436 +01:00] [INF] [19] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification: Started user data sync
[2024-12-07 13:58:38.482 +01:00] [ERR] [19] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification: An error has occurred in UserUpdateTimerCallback
System.InvalidCastException: Unable to cast object of type 'System.Guid' to type 'System.String'.
   at lambda_method1135(Closure, Object, Object)
   at LiteDB.BsonMapper.DeserializeObject(EntityMapper entity, Object obj, BsonDocument value)
   at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
   at LiteDB.LiteQueryable`1.<ToEnumerable>b__27_2(BsonDocument x)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at Jellyfin.Plugin.KodiSyncQueue.Data.DbRepo.SetUserInfoSync(List`1 dtos, List`1 itemRefs, String userId)
   at Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification.SaveUserChanges(List`1 dtos, List`1 itemRefs, String userName, String userId)
   at Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification.SendNotifications(IEnumerable`1 changes, List`1 itemRefs, CancellationToken cancellationToken)
   at Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification.UpdateTimerCallback(Object state)
```
Details of my installation:

- Jellyfin 10.10.3 (running in Docker)
- Kodi Sync Queue 13.0.0.0. I've already removed the plugin, restarted the Jellyfin container, installed the plugin again, and restarted the Jellyfin container again. This did not help.
- Client device: Ugoos AM6B+, CoreElec NG-21, running the Jellyfin for Kodi plugin version 1.0.6. "Enable Kodi Sync Queue"  is enabled. Playback mode of the plugin: Native (direct paths).

**Comment by crobibero** [comment]
Delete your kodisyncqueue.db and allow it to be recreated.

**Comment by pimw1** [comment]
Thank you so much, that solved the issue.

**Comment by crobibero** [comment]
This is now properly fixed with v14 of the plugin.

**Comment by pimw1** [comment]
Where can we find v14? Latest version displayed is v14 https://github.com/jellyfin/jellyfin-plugin-kodisyncqueue/releases

**Comment by pimw1** [comment]
V14 is somehow not visible in the plugin overview of Jellyfin?

**Comment by crobibero** [comment]
![image](https://github.com/user-attachments/assets/a2b8961b-e5dd-4f0f-9a71-db6499bc8c49)

Shows in my Jellyfin server.

**Comment by pimw1** [comment]
It's working now, after upgrading from 10.10.4 to 10.10.5
