### ISSUE TITLE
Latest nightlies break Kodisyncqueue plugin and a few others

### ISSUE THREAD

**Issue by Sp4rky001** [jellyfin/jellyfin-plugin-kodisyncqueue#21]
Not sure if this issue should be reported in the Jellyfin project or whether plugins system changed and plugins need to be updated.

In the last few nightlies, Kodi Sync Queue causes the server to stop booting with this error:

> [2020-03-28 12:46:59.379 -07:00] [INF] [1] Main: Jellyfin version: "10.5.0"
[2020-03-28 12:46:59.457 -07:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, C:\Server\Config\Jellyfin\log]"]
[2020-03-28 12:46:59.465 -07:00] [INF] [1] Main: Arguments: ["C:\Server\Daemons\Jellyfin\jellyfin.dll", "-d", "C:\Server\Config\Jellyfin"]
[2020-03-28 12:46:59.468 -07:00] [INF] [1] Main: Operating system: "Windows"
[2020-03-28 12:46:59.471 -07:00] [INF] [1] Main: Architecture: X64
[2020-03-28 12:46:59.473 -07:00] [INF] [1] Main: 64-Bit Process: True
[2020-03-28 12:46:59.474 -07:00] [INF] [1] Main: User Interactive: True
[2020-03-28 12:46:59.478 -07:00] [INF] [1] Main: Processor count: 4
[2020-03-28 12:46:59.480 -07:00] [INF] [1] Main: Program data path: "C:\Server\Config\Jellyfin"
[2020-03-28 12:46:59.482 -07:00] [INF] [1] Main: Web resources path: "C:\Server\Daemons\Jellyfin\jellyfin-web"
[2020-03-28 12:46:59.483 -07:00] [INF] [1] Main: Application directory: "C:\Server\Daemons\Jellyfin\"
[2020-03-28 12:46:59.747 -07:00] [INF] [1] ServerConfigurationManager: Setting cache path: "C:\Server\Config\Jellyfin\cache"
[2020-03-28 12:46:59.778 -07:00] [INF] [1] App: Loading assemblies
[2020-03-28 12:46:59.788 -07:00] [INF] [1] App: Loaded assembly "Jellyfin.Plugin.KodiSyncQueue, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null" from "C:\Server\Config\Jellyfin\plugins\Kodi Sync Queue\Jellyfin.Plugin.KodiSyncQueue.dll"
[2020-03-28 12:46:59.790 -07:00] [FTL] [1] Main: Error while starting server.
System.IO.FileNotFoundException: Could not load file or assembly 'MediaBrowser.Common, Version=10.5.2.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'MediaBrowser.Common, Version=10.5.2.0, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Emby.Server.Implementations.ApplicationHost.GetTypes(IEnumerable`1 assemblies)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Emby.Server.Implementations.ApplicationHost.DiscoverTypes()
   at Emby.Server.Implementations.ApplicationHost.InitAsync(IServiceCollection serviceCollection, IConfiguration startupConfig)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
>
>
>[2020-03-28 12:46:59.804 -07:00] [INF] [1] App: Disposing "CoreAppHost"
>[2020-03-28 12:46:59.807 -07:00] [INF] [2] Main: Received a SIGTERM signal, shutting down

**Comment by GhosterGAO** [comment]
it's a bug has just fixed on Jellyfin 10.5.3.
just see that link  https://github.com/jellyfin/jellyfin/pull/2730

but i still don't know what to do next~

**Comment by mcarlton00** [comment]
The released versions of plugins typically don't work on nightly releases of the server as things have changed internally.  We're working on a method to allow a separate nightly plugin repo that gives us a method to make this easier to work with, but it's not quite ready yet.

I know this is a rather old issue, but it applies (again) right now.  The released version (4.0.0) doesn't work on current nightly servers (soon to be release 10.6).  However, this has already been fixed in the repo.  But if that is released now, the new version of the plugin (5.0.0) won't work on the released version of the server (10.5.5).  This is the source of a lot of these plugin issues that doesn't have an easy solution.

Currently, if you're running a nightly server and want to use the Kodi Sync Queue plugin, you'll need to clone the repo and `dotnet build` it yourself, then transfer the generated dll file to your Jellyfin server.  Once 10.6 releases, we'll cut a new release of the Plugin and it will work properly from within the catalog again.
