### ISSUE TITLE
Can't install on fresh RPi4 install

### ISSUE THREAD

**Issue by podulator** [jellyfin/jellyfin-plugin-kodisyncqueue#32]
Hi there, I just did a fresh install of jellyfin on a fresh RPi4 OS install, and can't install this plugin.

Version: 10.6.4
Operating System: Linux
Architecture: Arm

Relevant info from logs 
```
[2020-12-06 16:35:07.330 +00:00] [ERR] Error processing request. URL: "http://192.168.178.4:8096/Packages/Installed/Kodi Sync Queue?AssemblyGuid=771e19d6-5385-4caf-b35c-28a0e865cf63&version=6.0.0.0"
MediaBrowser.Common.Extensions.ResourceNotFoundException: Package not found: Kodi Sync Queue
   at MediaBrowser.Api.PackageService.Post(InstallPackage request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2020-12-06 16:36:54.350 +00:00] [ERR] Error processing request. URL: "http://192.168.178.4:8096/Packages/Installed/Kodi Sync Queue?AssemblyGuid=771e19d6-5385-4caf-b35c-28a0e865cf63&version=6.0.0.0"
MediaBrowser.Common.Extensions.ResourceNotFoundException: Package not found: Kodi Sync Queue
   at MediaBrowser.Api.PackageService.Post(InstallPackage request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
[2020-12-06 16:37:18.807 +00:00] [ERR] Could not find handler for "/Packages/Installed/Kodi Sync Queue"
[2020-12-06 16:37:18.816 +00:00] [ERR] Error processing request: "Unable to find the specified file". URL: "http://192.168.178.4:8096/Packages/Installed/Kodi Sync Queue?AssemblyGuid=771e19d6-5385-4caf-b35c-28a0e865cf63&version=6.0.0.0"
[2020-12-06 16:37:24.798 +00:00] [ERR] Could not find handler for "/Packages/Installed/Kodi Sync Queue"
[2020-12-06 16:37:24.807 +00:00] [ERR] Error processing request: "Unable to find the specified file". URL: "http://192.168.178.4:8096/Packages/Installed/Kodi Sync Queue?"
[2020-12-06 16:37:32.020 +00:00] [ERR] Error processing request: "Access token is required". URL: "http://192.168.178.4:8096/Packages/Installed/"
[2020-12-06 16:38:08.469 +00:00] [ERR] Error processing request: "Access token is required". URL: "http://192.168.178.4:8096/Packages?PackageType=UserInstalled"
```
and
```
[2020-12-06 16:55:38.903 +00:00] [ERR] Error creating "Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification"
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
[2020-12-06 16:55:38.906 +00:00] [ERR] Error creating "Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification"
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
```

**Comment by mcarlton00** [comment]
Try to install version 5, not version 6.  Version 6 is for the upcoming 10.7 release of the server and shouldn't be showing, but there's a recently discovered bug that the filtering isn't working properly

**Comment by podulator** [comment]
Ah, that works perfectly , thanks!
