### ISSUE TITLE
Can't install it

### ISSUE THREAD

**Issue by DonLiborio** [jellyfin/jellyfin-plugin-kodisyncqueue#35]
I get this error in the log when I try to install it:

[2021-01-16 22:40:38.109 -03:00] [ERR] Error processing request. URL: "http://192.168.0.[xx]:8096/Packages/Installed/Kodi Sync Queue?AssemblyGuid=771e19d6-5385-4caf-b35c-28a0e865cf63&version=6.0.0.0"
MediaBrowser.Common.Extensions.ResourceNotFoundException: Package not found: Kodi Sync Queue
   at MediaBrowser.Api.PackageService.Post(InstallPackage request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)

**Comment by DonLiborio** [comment]
Nevermind! I found I have to install v5.
