### ISSUE TITLE
Plugin malfunctioned

### ISSUE THREAD

**Issue by zynexiz** [jellyfin/jellyfin-plugin-kodisyncqueue#49]
Using Jellyfin unstable release jellyfin-web-20210709 (stable don't work for me) on a CentOS server, and the plugin does not work. It's just saying malfunctioned on the plugin page, and Kodi says the plugin is not active. Is it compatibility issues with the unstable releases?
```

[2021-07-09 21:14:57.218 +02:00] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Error creating "Jellyfin.Plugin.KodiSyncQueue.Plugin"
System.TypeLoadException: Could not load type 'MediaBrowser.Model.Serialization.IJsonSerializer' from assembly 'MediaBrowser.Model, Version=10.8.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeConstructorInfo.get_Signature()
   at System.Reflection.RuntimeConstructorInfo.GetParametersNoCopy()
   at System.Reflection.RuntimeConstructorInfo.GetParameters()
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.Plugins.PluginManager.CreatePluginInstance(Type type)
[2021-07-09 21:14:57.221 +02:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Plugin "/var/lib/jellyfin/plugins/Kodi Sync Queue_6.0.0.0" has been disabled.
```

**Comment by crobibero** [comment]
Plugins are not built to target unstable Jellyfin releases.
