### ISSUE TITLE
jellyfin 10.10.0 + kody sync queue 12 UserUpdateTimerCallback error. Plugin not working.

### ISSUE THREAD

**Issue by Espindarga** [jellyfin/jellyfin-plugin-kodisyncqueue#99]
Since jellyfin server update to version 10.10.0 and kodisynkqueue plugin auto-updated to last version 12 I'm getting this error on jellyfin logs and plugin stops working

```
[2024-10-27 00:18:04.271 +02:00] [INF] [3] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification: Started user data sync
[2024-10-27 00:18:04.274 +02:00] [ERR] [3] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification: An error has occurred in UserUpdateTimerCallback
System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.Guid'.
   at lambda_method1524(Closure, Object, Object)
   at LiteDB.BsonMapper.DeserializeObject(EntityMapper entity, Object obj, BsonDocument value)
   at LiteDB.BsonMapper.Deserialize(Type type, BsonValue value)
   at LiteDB.LiteQueryable`1.<ToEnumerable>b__27_2(BsonDocument x)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at Jellyfin.Plugin.KodiSyncQueue.Data.DbRepo.SetUserInfoSync(List`1 dtos, List`1 itemRefs, String userId)
   at Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification.SaveUserChanges(List`1 dtos, List`1 itemRefs, String userName, String userId)
   at Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification.SendNotifications(IEnumerable`1 changes, List`1 itemRefs, CancellationToken cancellationToken)
   at Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification.UpdateTimerCallback(Object state)
   ```
   
Ops!
Sorry... editing...
As far I can see, plugin is working, at least partially. New content seems being correctly synced and it shows on kodi when started, but any change on item state, as unwatched to watched, throws error above and not synced to kodi.

**Comment by qwerty12** [comment]
I was getting these errors (and a different, but similar one when a client was trying to sync) until I shutdown my Jellyfin 10.10.0 server, deleted kodisyncqueue.db and kodisyncqueue-log.db from Jellyfin's data directory, and started the server again. I've not seen the errors since.
The plugin will create a new, clean kodisyncqueue.db file. Obviously, you'll have to do a full, probably time-consuming re-sync on your Kodi clients for them to reflect what you currently have on your server, so be warned. On the other hand, if you're not seeing anything you've newly added to Jellyfin show up in Kodi, you'd have to do that anyway.

I'm probably incorrect, but I think the [PR](https://github.com/jellyfin/jellyfin-plugin-kodisyncqueue/pull/97) that added 10.10.0 support changes the type of a field in the database to match the new JF version, but entries in the database made before 10.10.0 still have the old type and the plugin doesn't know what to do with them anymore.

**Comment by Espindarga** [comment]
It's working now as it should be. Thanks for the tip!

**Comment by crobibero** [comment]
Sorry to do this but I've reverted the database column back to being a string- so anyone who deleted the kodi databases will need to do that again.

**Comment by pdf** [comment]
Are migrations not a thing that can be done in plugins?
